# AWS CodeBuild

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  build:
    commands:
      - python3 -m venv ~/.venv
      - source ~/.venv/bin/activate
      - make install
      - make lint
      - make test
artifacts:
  files:
    - .ebextensions/options.config
    - main.py
    - requirements.txt