# AWS CodeBuild

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
  build:
    commands:
      - make install
      - make lint
      - make test
      - make format
artifacts:
  files:
    - .ebextensions/options.config
    - main.py
    - requirements.txt