version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker login
          command: echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
      - run:
          name: Install requirements
          command: make install
      - run:
          name: Lint with Pylint and Hadolint
          command: make lint
      - run:
          name: Test with Pytest
          command: make test
      - run:
          name: Format with Black
          command: make format

workflows:
  build_workflow:
    jobs:
      - Hold-for-Approval:
          type: approval
      - build:
          requires:
            - Hold-for-Approval