version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install requirements
          command: make install
      - run:
          name: Lint with Pylint and Hadolint
          command: make lint
      - run:
          name: Test with Pytest
          command: make test
      - run:
          name: Format with Black
          command: make format